#version: "3"
#services:
redis-server:
  image: "redis"
borker-web-service:
  image: "gitlab2-registry.viriyah.co.th/chakatponk/broker-web-service:v10"
  ports:
    - "4001:4001"
  links:
    - "redis-server:redis-server"
